### ISSUE TITLE
cannot import name 'izip'

### ISSUE THREAD

**Issue by JunfengZZZZhou** [pangyupo/mxnet_mtcnn_face_detection#52]
I use miniconda and activate environment python2.7, but it shows 

Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from mtcnn_detector import MtcnnDetector
  File "C:\ZhouJunfeng\project\facial-expression\mxnet_mtcnn_face_detection\mtcnn_detector.py", line 9, in <module>
    from itertools import izip
ImportError: cannot import name 'izip'

I have tried changing izip into zip, but that didn't work. What should I do?

**Comment by hanksoga** [comment]
delete from itertools import izip,and add izip = zip.

**Comment by JunfengZZZZhou** [comment]
> delete from itertools import izip,and add izip = zip.

It works! Thank you very much!

**Comment by cgntiger** [comment]
try:
    from itertools import izip
except ImportError:
    pass

**Comment by 1633347510** [comment]
please try 'izip=zip', it may be works~
