### ISSUE TITLE
src/ndarray/ndarray.cc:291: Check failed: from.shape() == to->shape() operands shape mismatch

### ISSUE THREAD

**Issue by enjoyyi00** [pangyupo/mxnet_mtcnn_face_detection#8]
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    results = detector.detect_face(img)
  File "/home/****/mxnet_mtcnn_face_detection/mtcnn_detector.py", line 291, in detect_face
    output = self.RNet.predict(input_buf)
  File "/home/****/mxnet_mtcnn_face_detection/mxnet/model.py", line 599, in predict
    self._init_predictor(data_shapes)
  File "/home/****/mxnet_mtcnn_face_detection/mxnet/model.py", line 531, in _init_predictor
    pred_exec.copy_params_from(self.arg_params, self.aux_params)
  File "/home/****/mxnet_mtcnn_face_detection/mxnet/executor.py", line 256, in copy_params_from
    array.astype(dst.dtype).copyto(dst)
  File "/home/****/mxnet_mtcnn_face_detection/mxnet/ndarray.py", line 499, in copyto
    return _internal._copyto(self, out=other)
  File "/home/****/mxnet_mtcnn_face_detection/mxnet/ndarray.py", line 1174, in unary_ndarray_function
    c_array(ctypes.c_char_p, [c_str(str(i)) for i in kwargs.values()])))
  File "/home/****/mxnet_mtcnn_face_detection/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [10:14:13] src/ndarray/ndarray.cc:291: Check failed: from.shape() == to->shape() operands shape mismatch

How to solve it, i just run your demo?

**Comment by bengouyy** [comment]
please update your mxnet and try again..
